spring:
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false
    spring.h2.console.settings.web-allow-others: false
  datasource:
    url: jdbc:h2:mem:apiDemo
    #url: jdbc:h2:file:/data/demo # In case we need to persist the data.
    username: 4dm1n
    password: p4ssw0rd
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect